AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: PresenQ-backend 
Globals:
    Function:
        Timeout: 3

Resources:
    PresenQFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: functions/
            Handler: app.lambda_handler
            Runtime: python3.8
            Policies: AmazonDynamoDBFullAccess
            Environment:
                Variables:
                    TABLE_NAME: !Ref PresenQTable
            Events:
                TaskList:
                    Type: Api
                    Properties:
                        Path: /boards/{board_id}
                        Method: get
                PutTask:
                    Type: Api
                    Properties: 
                        Path: /boards
                        Method: post
                Stream:
                    Type: DynamoDB
                    Properties:
                        Stream: !GetAtt PresenQTable.StreamArn
                        BatchSize: 10
                        StartingPosition: TRIM_HORIZON
    PresenQTable:
        Type: AWS::DynamoDB::Table
        Properties: 
            TableName: presenq_back
            AttributeDefinitions: 
                - AttributeName: board_id
                  AttributeType: S
                - AttributeName: created_at
                  AttributeType: S
            KeySchema: 
                - AttributeName: board_id
                  KeyType: HASH
                - AttributeName: created_at
                  KeyType: RANGE
            ProvisionedThroughput: 
                ReadCapacityUnits: 1
                WriteCapacityUnits: 1
            StreamSpecification:
                StreamViewType: NEW_IMAGE
